package net.tognola.diego.nuggets;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.io.IOException;
import java.util.List;

@DynamoDBTable(tableName = "nuggets_table")
public class Nugget {

    private static final String NUGGETS_TABLE_NAME = System.getenv("TABLE_NAME");
    private final DynamoDBAdapter db_adapter;
    private final DynamoDBMapper mapper;

    private String id;
    private String content;


    public Nugget() {
        this.db_adapter = DynamoDBAdapter.getInstance();
        DynamoDBMapperConfig mapperConfig = DynamoDBMapperConfig.builder()
                .withTableNameOverride(new DynamoDBMapperConfig.TableNameOverride(NUGGETS_TABLE_NAME))
                .build();
        this.mapper = this.db_adapter.createDbMapper(mapperConfig);
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }


    @DynamoDBRangeKey(attributeName = "content")
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }


    public List<Nugget> list() throws IOException {

        DynamoDBScanExpression scanExp = new DynamoDBScanExpression();
        List<Nugget> nuggets = this.mapper.scan(Nugget.class, scanExp);

        for (Nugget nugget : nuggets) {
            System.out.println("-> " + nugget.toString());
        }

        return nuggets;

    }

}
